approve_by_comment: true
approve_regex: ^(Approved|LGTM)
reject_regex: ^Rejected
reset_on_push: true
reviewers:
  -
    name: "GRIP Merge Approvers"
    required: 1
    teams:
      - grip-merge-approvers
