approve_by_comment: true
approve_regex: ^(Approved|LGTM)
author_approval: required
reject_regex: ^Rejected
reset_on_push: true
reviewers:
  -
    name: "GRIP Merge Approvers"
    required: 3
    teams:
      - grip
