/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer */

#ifndef _Included_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
#define _Included_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
 * Method:    setMatSource
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer_setMatSource
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
 * Method:    setNumSource
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer_setNumSource
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
 * Method:    process
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer_process
  (JNIEnv *, jobject);

/*
 * Class:     edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
 * Method:    getMatNative
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer_getMatNative
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
 * Method:    getDouble
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer_getDouble
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
 * Method:    getBoolean
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer_getBoolean
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
 * Method:    setCondition
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer_setCondition
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer_dispose
  (JNIEnv *, jobject);

/*
 * Class:     edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
 * Method:    getSizeOrPoint
 * Signature: (Ljava/lang/String;Z)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer_getSizeOrPoint
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
 * Method:    getBlobs
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer_getBlobs
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
 * Method:    getNumContours
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer_getNumContours
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
 * Method:    getContours
 * Signature: (Ljava/lang/String;[J)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer_getContours
  (JNIEnv *, jobject, jstring, jlongArray);

/*
 * Class:     edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
 * Method:    getLines
 * Signature: (Ljava/lang/String;)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer_getLines
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
