/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer */

#ifndef _Included_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
#define _Included_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
 * Method:    process
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer_process
  (JNIEnv *, jobject);

/*
 * Class:     edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
 * Method:    getMatFile
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer_getMatFile
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
 * Method:    getDouble
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer_getDouble
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
 * Method:    getBoolean
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer_getBoolean
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
 * Method:    setCondition
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer_setCondition
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
 * Method:    setMatSource
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer_setMatSource
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_wpi_grip_ui_codegeneration_tools_CppPipelineInterfacer_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
